### PR TITLE
Add pipeline switch into update_docker (as update_package_properties)

### LINKED ISSUE #147: Add pipeline switch for update_docker
update_package_properties scripts has a pipeline parameter to be able to be executed both manual and in pipeline. 
Add this feature in update_docker
when pipeline is true, no clone operation is performed since pipeline alredy clones the referenced repo (i.e. docker)
when false, first repo (i.e docker repo) is cloned, operation performed and code is deleted after finish execution

### PR DESCRIPTION
**Pull request by gurkanindibay**
Fixes #147 
Blocked by #150

### CODE REVIEW

**Comment by hanefi** [comment]
@gurkanindibay did you check that these changes are ok
- [ ] in your dev machine
- [ ] in GitHub Actions pipeline

I want to test them both before approval. The code changes seem to be fine when I look at it at a high-level

**Comment by gurkanindibay** [comment]
> @gurkanindibay did you check that these changes are ok
> 
> * [x]  in your dev machine
> * [x]  in GitHub Actions pipeline
> 
> I want to test them both before approval. The code changes seem to be fine when I look at it at a high-level
I checked them both on my laptop and on Github actions
Github actions successful execution
https://github.com/citusdata/docker/actions/runs/1112518675


> @gurkanindibay did you check that these changes are ok
> 
> * [x]  in your dev machine
> * [x]  in GitHub Actions pipeline
> 
> I want to test them both before approval. The code changes seem to be fine when I look at it at a high-level
Test results are as below
image

https://github.com/citusdata/docker/actions/runs/1112518675

**Comment by gurkanindibay** [comment]
Removed pipeline parameter check to delete cloned code

**Comment by hanefi** [comment]
Needs a rebase, and force push.

**Review by hanefi — APPROVED** [review]

**Pull request merged**
